name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    name: buildPresentations
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-21.11
      
      - name: Build package
        run: nix-shell --run 'sbt validate'
